[package]
authors = ["Jorge Aparicio <japaricious@gmail.com>"]
name = "criterion"
version = "0.0.0"

[dependencies]
itertools = "0.4.7"
log = "0.3.5"
rustc-serialize = "0.3.16"

[dependencies.criterion_macros]
path = "macros"

[dependencies.simplot]
git = "https://github.com/japaric/simplot.rs"

[dependencies.stats]
git = "https://github.com/japaric/stats.rs"

[dev-dependencies]
walkdir = "0.1.5"
