[package]

authors = ["Jorge Aparicio <japaricious@gmail.com>"]
name = "criterion"
version = "0.0.0"

[dependencies.criterion_macros]
path = "macros"

[dependencies.log]
git = "https://github.com/rust-lang/log"

[dependencies.rustc-serialize]
git = "https://github.com/rust-lang/rustc-serialize"

[dependencies.simplot]
git = "https://github.com/japaric/simplot.rs"

[dependencies.space]
git = "https://github.com/japaric/space.rs"

[dependencies.stats]
git = "https://github.com/japaric/stats.rs"
branch = "no-simd"

[dependencies.time]
git = "https://github.com/rust-lang/time"
