[package]
authors = ["Jorge Aparicio <japaricious@gmail.com>"]
name = "criterion"
version = "0.0.0"

[dependencies]
criterion-plot = {git = "https://github.com/japaric/simplot.rs"}
criterion-stats = {git = "https://github.com/japaric/stats.rs"}
itertools = "0.4.7"
log = "0.3.5"
rustc-serialize = "0.3.16"

[dev-dependencies]
criterion-macros = { path = "macros" }
walkdir = "0.1.5"
