[package]
authors = ["Jorge Aparicio <japaricious@gmail.com>", "Brook Heisler <brookheisler@gmail.com>"]
name = "criterion"
version = "0.2.4"

description = "Statistics-driven micro-benchmarking library"
homepage = "https://japaric.github.io/criterion.rs/book/index.html"
repository = "https://github.com/japaric/criterion.rs"
readme = "README.md"
keywords = ["criterion", "benchmark"]
categories = ["development-tools::profiling"]
license = "Apache-2.0/MIT"

[dependencies]
criterion-plot = { path="plot", version="0.2.4", optional = true }
criterion-stats = { path="stats", version="0.2.4" }
failure = "0.1.1"
failure_derive = "0.1.1"
itertools = "0.7"
itertools-num = "0.1"
log = "0.4"
simplelog = "^0.5.0"
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
atty = "0.2"
clap = "2.29"
handlebars = { version = "0.32", optional = true }
csv = "1.0"
walkdir = "2.2"

[dev-dependencies]
tempdir = "0.3"

[badges]
travis-ci = { repository = "japaric/criterion.rs" }
appveyor = { repository = "japaric/criterion.rs", id = "4255ads9ctpupcl2" }
coveralls = { repository = "japaric/criterion.rs" }
maintenance = { status = "passively-maintained" }

[features]
real_blackbox = []
html_reports = ["handlebars", "criterion-plot"]
default = ["html_reports"]

[workspace]

[[bench]]
name = "bench_main"
harness = false

[lib]
bench = false
