[package]
authors = ["Jorge Aparicio <japaricious@gmail.com>", "Brook Heisler <brookheisler@gmail.com>"]
name = "criterion"
version = "0.3.1"
edition = "2018"

description = "Statistics-driven micro-benchmarking library"
homepage = "https://bheisler.github.io/criterion.rs/book/index.html"
repository = "https://github.com/bheisler/criterion.rs"
readme = "README.md"
keywords = ["criterion", "benchmark"]
categories = ["development-tools::profiling"]
license = "Apache-2.0/MIT"
exclude = ["book/*"]

[dependencies]
lazy_static = "1.4"
criterion-plot = { path="plot", version="0.4.1" }
itertools = "0.8"
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
atty = "0.2"
clap = { version = "2.33", default-features = false }
csv = "1.1"
walkdir = "2.3"
tinytemplate = "1.0"
cast = "0.2"
num-traits = "0.2"
oorandom = "11.1"
rayon = "1.3"
regex = { version = "1.3", default-features = false, features = ["std"] }

[dependencies.plotters]
version = "^0.2.12"
default-features = false
features = ["svg", "area_series", "line_series"] 

[dev-dependencies]
tempdir = "0.3.7"
approx = "0.3"
quickcheck = { version = "0.9", default-features = false }
rand = "0.7"

[badges]
travis-ci = { repository = "bheisler/criterion.rs" }
appveyor = { repository = "bheisler/criterion.rs", id = "4255ads9ctpupcl2" }
maintenance = { status = "passively-maintained" }

[features]
real_blackbox = []
default = []

[workspace]

[[bench]]
name = "bench_main"
harness = false

[lib]
bench = false
